---
new_page_extension: md
auto_deploy: false
admin_path: "/admin/"
webhook_url: 
sections:
- type: document
  path: pages/index.md
  label: Home Page
- type: document
  path: _data/courses.yml
  label: Courses
- type: document
  path: pages/faculty.md
  label: Faculty
- type: document
  path: pages/assignments.md
  label: Assignments
- type: document
  path: pages/news.md
  label: News/Updates
- type: document
  path: pages/contact.md
  label: Contact Us
- type: document
  path: pages/testimonials.md
  label: Student Testimonials
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
